services:

  web-app:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JAREK
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/var/lib/pgadmin

    ports:
    - "5050:80"
    networks:
    - db
    restart: unless-stopped

networks:
  db:
    driver:  bridge

volumes:
  db:
  pgadmin:
